USE `argos`;

INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('1', 'Ambiente', '', NULL);
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('2', 'Electrodomésticos', 'Electrodomésticos', '1');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('3', 'Campanas', 'Campanas', '2');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('4', 'Estufas', 'Estufas', '2');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('5', 'Refrigeradores', 'Refrigeradores', '2');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('6', 'Licuadoras', 'Licuadoras', '2');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('7', 'Tostadores', 'Tostadores', '2');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('8', 'Extractores', 'Extractores', '2');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('9', 'Batidora', 'Batidora', '2');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('10', 'Hornos', 'Hornos', '2');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('11', 'Sandwicheras', 'Sandwicheras', '2');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('12', 'Parrillas eléctricas', 'Parrillas eléctricas', '2');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('13', 'Dispensador de agua', 'Dispensador de agua', '2');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('14', 'Cafeteras', 'Cafeteras', '2');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('15', 'Lavadora', 'Lavadora', '2');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('16', 'Climas', 'Climas (calefactor, ventilador, aire acondicionado)', '2');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('17', 'Cocina', 'Cocina', '1');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('18', 'Canastos', 'Canastos', '17');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('19', 'Utensilios de cocina', 'Utensilios de cocina', '17');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('20', 'Ollas', 'Ollas', '17');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('21', 'Contenedores', 'Contenedores', '17');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('22', 'Plásticos', 'Plásticos', '21');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('23', 'Cerámica', 'Cerámica', '21');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('24', 'Madera', 'Madera', '21');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('25', 'Cristal', 'Cristal', '21');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('26', 'Metal', 'Metal', '21');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('27', 'Especieros', 'Especieros', '17');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('28', 'Repostería', 'Repostería', '17');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('29', 'Jarras', 'Jarras', '17');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('30', 'Fruteros', 'Fruteros', '17');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('31', 'Paneras', 'Paneras', '17');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('32', 'Dispensador de agua', 'Dispensador de agua', '17');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('33', 'Tablas de picar', 'Tablas de picar', '17');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('34', 'Trapos de cocina', 'Trapos de cocina', '17');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('35', 'Guantes y agarraderas', 'Guantes y agarraderas', '17');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('36', 'Contenedores', 'Contenedores', '1');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('37', 'Metal', 'Metal', '36');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('38', 'Plástico', 'Plástico', '36');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('39', 'Madera', 'Madera', '36');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('40', 'Instalaciones', 'Instalaciones', '1');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('41', 'Eléctrico', 'Eléctrico', '40');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('42', 'Sanitario', 'Sanitario', '40');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('43', 'Hidráulico', 'Hidráulico', '40');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('44', 'Funerario- Cementerio', 'Funerario- Cementerio', '1');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('45', 'Religioso', 'Religioso', '1');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('46', 'Hospital', 'Hospital', '1');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('47', 'Escolar', 'Escolar', '1');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('48', 'Artículos de escritorio y oficina', 'Artículos de escritorio y oficina', '1');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('49', 'Lotes de impresos,audio y video', 'Lotes de impresos,audio y video', '1');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('50', 'Lote de Archivo muerto', 'Lote de Archivo muerto', '49');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('51', 'Lote de revistas', 'Lote de revistas', '49');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('52', 'Lote de periódico', 'Lote de periódico', '49');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('53', 'Libros', 'Libros', '49');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('54', 'DVD', 'DVD', '49');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('55', 'CD', 'CD', '49');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('56', 'Acetatos', 'Acetatos', '49');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('57', 'Casettes', 'Casettes', '49');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('58', 'VHS', 'VHS', '49');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('59', 'BETTA', 'BETTA', '49');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('60', 'Baño', 'Baño', '1');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('61', 'Cuadros', 'Cuadros', '1');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('62', 'Repisas', 'Repisas', '1');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('63', 'Portaretratos', 'Portaretratos', '1');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('64', 'Bebés', 'Bebés', '1');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('65', 'Juguetes y juegos', 'Juguetes y juegos', '1');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('66', 'Electrónicos', 'Electrónicos', '1');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('67', 'Plasmas', 'Plasmas', '66');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('68', 'Tv', 'Tv', '66');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('69', 'Pantallas', 'Pantallas', '66');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('70', 'Estereos', 'Estereos', '66');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('71', 'Grabadoras', 'Grabadoras', '66');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('72', 'Radios', 'Radios', '1');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('73', 'Antiguos', 'Antiguos', '72');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('74', 'Contemporáneos', 'Contemporáneos', '72');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('75', 'Bocinas', 'Bocinas', '66');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('76', 'Consolas', 'Consolas', '66');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('77', 'Reproductor de DVD', 'Reproductor de DVD', '66');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('78', 'Videocaseteras', 'Videocaseteras', '66');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('79', 'Teléfonos', 'Teléfonos', '1');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('80', 'Fijos', 'Fijos', '79');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('81', 'Fax', 'Fax', '79');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('82', 'Interfone', 'Interfone', '79');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('83', 'Pared', 'Pared', '79');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('84', 'Públicos', 'Públicos', '79');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('85', 'Percheros', 'Percheros', '1');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('86', 'Espejos', 'Espejos', '1');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('87', 'Pie', 'Pie', '86');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('88', 'Pared', 'Pared', '86');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('89', 'Mesa', 'Mesa', '86');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('90', 'Relojes', 'Relojes', '1');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('91', 'Pie', 'Pie', '90');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('92', 'Pared', 'Pared', '90');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('93', 'Mesa', 'Mesa', '90');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('94', 'Celosías', 'Celosías', '1');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('95', 'Chimeneas', 'Chimeneas', '1');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('96', 'Tapetes', 'Tapetes', '1');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('97', 'Chicos', 'Chicos', '96');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('98', 'Medianos', 'Medianos', '96');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('99', 'Grandes', 'Grandes', '96');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('100', 'Unilas', 'Unilas', '1');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('101', 'Letreros', 'Letreros', '1');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('102', 'Luminosos', 'Luminosos', '101');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('103', 'Señalética', 'Señalética', '101');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('104', 'Figuras Decorativas', 'Figuras Decorativas', '1');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('105', 'Floreros', 'Floreros', '104');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('106', 'Esculturas', 'Esculturas', '104');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('107', 'Figuras Porcelanas', 'Figuras Porcelanas', '104');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('108', 'Jarrones', 'Jarrones', '104');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('109', 'Cristalería', 'Cristalería', '104');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('110', 'Mobiles colgantes', 'Mobiles colgantes', '104');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('111', 'Esferas', 'Esferas', '104');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('112', 'Ceniceros', 'Ceniceros', '104');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('113', 'Luminarias', 'Luminarias', '1');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('114', 'Lámparas', 'Lámparas', '113');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('115', 'Linternas', 'Linternas', '114');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('116', 'De pie', 'De pie', '114');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('117', 'Mesa', 'Mesa', '114');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('118', 'De buró', 'De buró', '114');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('119', 'Arbotantes', 'Arbotantes', '114');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('120', 'Colgantes', 'Colgantes', '114');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('121', 'Velas', 'Velas', '113');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('122', 'Porta velas', 'Porta velas', '121');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('123', 'Candiles', 'Candiles', '121');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('124', 'Faroles', 'Faroles', '121');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('125', 'Antorchas', 'Antorchas', '121');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('126', 'Telas, telones', 'Telas, telones', '1');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('127', 'Catres', 'Catres', '1');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('128', 'Ocios talleres', 'Ocios talleres', '1');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('129', 'Herramientas-Máquinas', 'Herramientas-Máquinas', '128');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('130', 'Flores y plantas artificiales', 'Flores y plantas artificiales', '1');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('131', 'Flores', 'Flores', '130');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('132', 'Plantas', 'Plantas', '130');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('133', 'Macetas', 'Macetas', '130');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('134', 'Botes de basura', 'Botes de basura', '1');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('135', 'Baules', 'Baules', '1');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('136', 'Deportivos', 'Deportivos', '1');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('137', 'Servicio de bar', 'Servicio de bar', '1');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('138', 'Servicio de cafetería', 'Servicio de cafetería', '1');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('139', 'Servicio de mesa', 'Servicio de mesa', '1');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('140', 'Vasos', 'Vasos', '139');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('141', 'Copas', 'Copas', '139');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('142', 'Vajillas', 'Vajillas', '139');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('143', 'Cubiertos', 'Cubiertos', '139');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('144', 'Servilleteros', 'Servilleteros', '139');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('145', 'Bajo platos', 'Bajo platos', '139');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('146', 'Charolas', 'Charolas', '1');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('147', 'Blancos', 'Blancos', '1');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('148', 'Cama', 'Cama', '147');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('149', 'Sábanas', 'Sábanas', '148');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('150', 'King size', 'King size', '149');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('151', 'Queen size', 'Queen size', '149');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('152', 'Matrimonial', 'Matrimonial', '149');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('153', 'Individual', 'Individual', '149');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('154', 'Cuna', 'Cuna', '149');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('155', 'Edredones', 'Edredones', '148');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('156', 'King size', 'King size', '155');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('157', 'Queen size', 'Queen size', '155');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('158', 'Matrimonial', 'Matrimonial', '155');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('159', 'Individual', 'Individual', '155');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('160', 'Cuna', 'Cuna', '155');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('161', 'Duvet', 'Duvet', '148');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('162', 'King size', 'King size', '161');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('163', 'Queen size', 'Queen size', '161');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('164', 'Matrimonial', 'Matrimonial', '161');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('165', 'Individual', 'Individual', '161');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('166', 'Cuna', 'Cuna', '161');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('167', 'Cobijas', 'Cobijas', '148');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('168', 'King size', 'King size', '167');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('169', 'Queen size', 'Queen size', '167');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('170', 'Matrimonial', 'Matrimonial', '167');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('171', 'Individual', 'Individual', '167');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('172', 'Cuna', 'Cuna', '167');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('173', 'Colchonetas', 'Colchonetas', '148');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('174', 'Frazadas', 'Frazadas', '148');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('175', 'Almohadas', 'Almohadas', '148');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('176', 'Mesa', 'Mesa', '147');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('177', 'Servilletas', 'Servilletas', '176');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('178', 'Manteles', 'Manteles', '176');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('179', 'Redondos', 'Redondos', '178');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('180', 'Cuadrados', 'Cuadrados', '178');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('181', 'Rectangulares', 'Rectangulares', '178');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('182', 'Individuales', 'Individuales', '178');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('183', 'Caminos de mesa', 'Caminos de mesa', '176');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('184', 'Carpetas', 'Carpetas', '176');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('185', 'Cojines', 'Cojines', '147');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('186', 'Cortinas', 'Cortinas', '147');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('187', 'Toallas', 'Toallas', '147');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('188', 'Equipo de cómputo', 'Equipo de cómputo', '147');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('189', 'Computadoras de escritorio', 'Computadoras de escritorio', '188');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('190', 'Scanner', 'Scanner', '188');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('191', 'impresora', 'impresora', '188');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('192', 'Copiadora', 'Copiadora', '188');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('193', 'Adornos temáticos', 'Adornos temáticos', '1');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('194', 'Varios', 'Varios', '1');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('195', 'Muebles', 'Muebles', NULL);
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('196', 'Bancos', 'Bancos', '195');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('197', 'Sillas', 'Sillas', '195');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('198', 'Metal', 'Metal', '197');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('199', 'Madera', 'Madera', '197');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('200', 'Plástico', 'Plástico', '197');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('201', 'Tapiz', 'Tapiz', '197');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('202', 'Mesas', 'Mesas', '195');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('203', 'Mesas trabajo', 'Mesas trabajo', '202');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('204', 'Mesas periqueras', 'Mesas periqueras', '202');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('205', 'Mesas comensal', 'Mesas comensal', '202');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('206', 'Redondas', 'Redondas', '205');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('207', 'Cuadradas', 'Cuadradas', '205');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('208', 'Irregulares', 'Irregulares', '205');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('209', 'Poligonales', 'Poligonales', '205');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('210', 'Mesas de centro', 'Mesas de centro', '202');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('211', 'Redondas', 'Redondas', '210');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('212', 'Cuadradas', 'Cuadradas', '210');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('213', 'Irregulares', 'Irregulares', '210');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('214', 'Poligonales', 'Poligonales', '210');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('215', 'Mesas de laterales', 'Mesas de laterales', '202');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('216', 'Mesas de esquineras', 'Mesas de esquineras', '202');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('217', 'Mesas de juego', 'Mesas de juego', '202');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('218', 'Muebles de jardín y playa', 'Muebles de jardín y playa', '195');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('219', 'Consolas', 'Consolas', '195');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('220', 'Credenzas', 'Credenzas', '195');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('221', 'Vitrinas', 'Vitrinas', '195');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('222', 'Mostradores', 'Mostradores', '195');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('223', 'Sofá - cama', 'Sofá - cama', '195');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('224', 'Loveseat', 'Loveseat', '195');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('225', 'Sala Modular', 'Sala Modular', '195');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('226', 'Sillón individual', 'Sillón individual', '195');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('227', 'Sillón 3 y 4 plazas', 'Sillón 3 y 4 plazas', '195');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('228', 'Puff', 'Puff', '195');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('229', 'Diván', 'Diván', '195');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('230', 'Taburetes', 'Taburetes', '195');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('231', 'Libreros', 'Libreros', '195');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('232', 'Barras', 'Barras', '195');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('233', 'Gabinetes', 'Gabinetes', '195');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('234', 'Estanterías', 'Estanterías', '195');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('235', 'Lockers', 'Lockers', '234');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('236', 'Racks', 'Racks', '234');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('237', 'Cocina integral', 'Cocina integral', '195');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('238', 'Alacenas', 'Alacenas', '195');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('239', 'Estanterías Lockers', 'Estanterías Lockers', '195');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('240', 'Racks', 'Racks', '195');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('241', 'Retretes', 'Retretes', '195');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('242', 'Mingitorios', 'Mingitorios', '195');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('243', 'Lavabos', 'Lavabos', '195');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('244', 'Tinas', 'Tinas', '195');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('245', 'Cancelería', 'Cancelería', '195');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('246', 'Escritorios', 'Escritorios', '195');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('247', 'Archiveros', 'Archiveros', '195');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('248', 'Bufettes', 'Bufettes', '195');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('249', 'Muebles de tv', 'Muebles de tv', '195');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('250', 'Barras', 'Barras', '195');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('251', 'Camas', 'Camas', '195');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('252', 'Cabecera, pieceras', 'Cabecera, pieceras', '251');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('253', 'Base', 'Base', '251');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('254', 'Colchón', 'Colchón', '251');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('255', 'Cunas', 'Cunas', '251');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('256', 'Literas', 'Literas', '251');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('257', 'Cajoneras', 'Cajoneras', '195');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('258', 'Armarios', 'Armarios', '195');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('259', 'Roperos', 'Roperos', '195');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('260', 'Buroes', 'Buroes', '195');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('261', 'Tocadores', 'Tocadores', '195');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('262', 'Jugueteros', 'Jugueteros', '195');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('263', 'Bancas', 'Bancas', '195');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('264', 'Muebles de hospital', 'Muebles de hospital', '195');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('265', 'Especiales', 'Especiales', '195');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('266', 'Utilería', 'Utilería', NULL);
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('267', 'Escritura', 'Escritura', '266');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('268', 'Joyería', 'Joyería', '266');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('269', 'Maculina', 'Maculina', '268');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('270', 'Femenina', 'Femenina', '268');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('271', 'Relojes de pulso', 'Relojes de pulso', '266');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('272', 'Gadget', 'Gadget', '266');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('273', 'Laptop', 'Laptop', '272');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('274', 'Tabletas', 'Tabletas', '272');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('275', 'Iphode', 'Iphode', '272');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('276', 'Biper', 'Biper', '272');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('277', 'Celulares', 'Celulares', '272');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('278', 'Grabadoras', 'Grabadoras', '272');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('279', 'Audio portátiles', 'Audio portátiles', '272');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('280', 'Audífonos', 'Audífonos', '272');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('281', 'Carcasas', 'Carcasas', '266');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('282', 'Portafolios', 'Portafolios', '266');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('283', 'Maletas', 'Maletas', '266');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('284', 'Mochilas', 'Mochilas', '266');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('285', 'Bolsos', 'Bolsos', '266');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('286', 'Carteras', 'Carteras', '266');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('287', 'Llaveros', 'Llaveros', '266');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('288', 'Gafetes', 'Gafetes', '266');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('289', 'Dinero', 'Dinero', '266');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('290', 'Placas oficiales', 'Placas oficiales', '266');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('291', 'Paraguas', 'Paraguas', '266');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('292', 'Bastones', 'Bastones', '266');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('293', 'Lentes', 'Lentes', '266');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('294', 'Gafas', 'Gafas', '266');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('295', 'Artículos de belleza', 'Artículos de belleza', '266');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('296', 'Artículos de limpieza', 'Artículos de limpieza', '266');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('297', 'Equipo fotográfico', 'Equipo fotográfico', '266');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('298', 'Chapuzas', 'Chapuzas', '266');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('299', 'Armas', 'Armas', '266');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('300', 'Otros', 'Otros', '266');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('301', 'Vestuario', 'Vestuario', NULL);
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('302', 'Masculino', 'Masculino', '301');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('303', 'Hombre', 'Hombre', '302');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('304', 'Pantalones', 'Pantalones', '303');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('305', 'Chico', 'Chico', '304');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('306', 'Mediano', 'Mediano', '304');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('307', 'Grande', 'Grande', '304');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('308', 'Batas', 'Batas', '303');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('309', 'Chico', 'Chico', '308');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('310', 'Mediano', 'Mediano', '308');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('311', 'Grande', 'Grande', '308');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('312', 'Camisas', 'Camisas', '303');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('313', 'Chico', 'Chico', '312');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('314', 'Mediano', 'Mediano', '312');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('315', 'Grande', 'Grande', '312');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('316', 'Playeras', 'Playeras', '303');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('317', 'Chico', 'Chico', '316');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('318', 'Mediano', 'Mediano', '316');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('319', 'Grande', 'Grande', '316');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('320', 'Smoking', 'Smoking', '303');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('321', 'Chico', 'Chico', '320');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('322', 'Mediano', 'Mediano', '320');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('323', 'Grande', 'Grande', '320');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('324', 'Traje', 'Traje', '303');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('325', 'Chico', 'Chico', '324');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('326', 'Mediano', 'Mediano', '324');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('327', 'Grande', 'Grande', '324');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('328', 'Sueter', 'Sueter', '303');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('329', 'Chico', 'Chico', '328');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('330', 'Mediano', 'Mediano', '328');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('331', 'Grande', 'Grande', '328');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('332', 'Chalecos', 'Chalecos', '303');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('333', 'Chico', 'Chico', '332');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('334', 'Mediano', 'Mediano', '332');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('335', 'Grande', 'Grande', '332');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('336', 'Bermudas', 'Bermudas', '303');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('337', 'Chico', 'Chico', '336');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('338', 'Mediano', 'Mediano', '336');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('339', 'Grande', 'Grande', '336');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('340', 'Ropa interior', 'Ropa interior', '303');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('341', 'Chico', 'Chico', '340');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('342', 'Mediano', 'Mediano', '340');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('343', 'Grande', 'Grande', '340');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('344', 'Deportiva', 'Deportiva', '303');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('345', 'Chico', 'Chico', '344');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('346', 'Mediano', 'Mediano', '344');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('347', 'Grande', 'Grande', '344');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('348', 'Pijamas', 'Pijamas', '303');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('349', 'Chico', 'Chico', '348');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('350', 'Mediano', 'Mediano', '348');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('351', 'Grande', 'Grande', '348');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('352', 'Chamarras', 'Chamarras', '303');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('353', 'Chico', 'Chico', '352');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('354', 'Mediano', 'Mediano', '352');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('355', 'Grande', 'Grande', '352');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('356', 'Abrigos', 'Abrigos', '303');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('357', 'Chico', 'Chico', '356');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('358', 'Mediano', 'Mediano', '356');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('359', 'Grande', 'Grande', '356');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('360', 'Accesorios', 'Accesorios', '303');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('361', 'Pañuelos', 'Pañuelos', '360');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('362', 'Moños', 'Moños', '360');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('363', 'Gasneé', 'Gasneé', '360');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('364', 'Corbatas', 'Corbatas', '360');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('365', 'Bufanda', 'Bufanda', '360');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('366', 'Guantes', 'Guantes', '360');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('367', 'Sombreros', 'Sombreros', '360');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('368', 'Cinturones', 'Cinturones', '360');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('369', 'Calzado', 'Calzado', '303');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('370', 'Botas*', 'Botas*', '369');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('371', 'Tenis*', 'Tenis*', '369');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('372', 'Sandalias*', 'Sandalias*', '369');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('373', 'Pantufla*', 'Pantufla*', '369');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('374', 'Zapato*', 'Zapato*', '369');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('375', 'Especiales*', 'Especiales*', '369');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('376', 'Niño', 'Niño', '302');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('377', 'Pantalones', 'Pantalones', '376');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('378', 'Chico', 'Chico', '377');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('379', 'Mediano', 'Mediano', '377');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('380', 'Grande', 'Grande', '377');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('381', 'Batas', 'Batas', '376');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('382', 'Chico', 'Chico', '381');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('383', 'Mediano', 'Mediano', '381');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('384', 'Grande', 'Grande', '381');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('385', 'Camisas', 'Camisas', '376');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('386', 'Chico', 'Chico', '385');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('387', 'Mediano', 'Mediano', '385');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('388', 'Grande', 'Grande', '385');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('389', 'Playeras', 'Playeras', '376');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('390', 'Chico', 'Chico', '389');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('391', 'Mediano', 'Mediano', '389');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('392', 'Grande', 'Grande', '389');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('393', 'Smoking', 'Smoking', '376');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('394', 'Chico', 'Chico', '393');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('395', 'Mediano', 'Mediano', '393');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('396', 'Grande', 'Grande', '393');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('397', 'Traje', 'Traje', '376');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('398', 'Chico', 'Chico', '397');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('399', 'Mediano', 'Mediano', '397');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('400', 'Grande', 'Grande', '397');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('401', 'Sueter', 'Sueter', '376');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('402', 'Chico', 'Chico', '401');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('403', 'Mediano', 'Mediano', '401');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('404', 'Grande', 'Grande', '401');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('405', 'Chalecos', 'Chalecos', '376');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('406', 'Chico', 'Chico', '405');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('407', 'Mediano', 'Mediano', '405');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('408', 'Grande', 'Grande', '405');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('409', 'Bermudas', 'Bermudas', '376');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('410', 'Chico', 'Chico', '409');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('411', 'Mediano', 'Mediano', '409');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('412', 'Grande', 'Grande', '409');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('413', 'Ropa interior', 'Ropa interior', '376');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('414', 'Chico', 'Chico', '413');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('415', 'Mediano', 'Mediano', '413');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('416', 'Grande', 'Grande', '413');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('417', 'Deportiva', 'Deportiva', '376');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('418', 'Chico', 'Chico', '417');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('419', 'Mediano', 'Mediano', '417');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('420', 'Grande', 'Grande', '417');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('421', 'Pijamas', 'Pijamas', '376');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('422', 'Chico', 'Chico', '421');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('423', 'Mediano', 'Mediano', '421');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('424', 'Grande', 'Grande', '421');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('425', 'Chamarras', 'Chamarras', '376');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('426', 'Chico', 'Chico', '425');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('427', 'Mediano', 'Mediano', '425');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('428', 'Grande', 'Grande', '425');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('429', 'Abrigos', 'Abrigos', '376');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('430', 'Chico', 'Chico', '429');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('431', 'Mediano', 'Mediano', '429');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('432', 'Grande', 'Grande', '429');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('433', 'Accesorios', 'Accesorios', '376');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('434', 'Pañuelos', 'Pañuelos', '433');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('435', 'Moños', 'Moños', '433');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('436', 'Gasneé', 'Gasneé', '433');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('437', 'Corbatas', 'Corbatas', '433');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('438', 'Bufanda', 'Bufanda', '433');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('439', 'Guantes', 'Guantes', '433');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('440', 'Sombreros', 'Sombreros', '433');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('441', 'Cinturones', 'Cinturones', '433');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('442', 'Calzado', 'Calzado', '376');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('443', 'Botas*', 'Botas*', '442');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('444', 'Tenis*', 'Tenis*', '442');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('445', 'Sandalias*', 'Sandalias*', '442');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('446', 'Pantufla*', 'Pantufla*', '442');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('447', 'Zapato*', 'Zapato*', '442');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('448', 'Especiales*', 'Especiales*', '442');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('449', 'Femenino', 'Femenino', '301');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('450', 'Mujer', 'Mujer', '449');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('451', 'Blusas', 'Blusas', '450');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('452', 'Chico', 'Chico', '451');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('453', 'Mediano', 'Mediano', '451');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('454', 'Grande', 'Grande', '451');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('455', 'Vestidos', 'Vestidos', '450');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('456', 'Chico', 'Chico', '455');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('457', 'Mediano', 'Mediano', '455');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('458', 'Grande', 'Grande', '455');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('459', 'Vestido de noche', 'Vestido de noche', '450');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('460', 'Chico', 'Chico', '459');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('461', 'Mediano', 'Mediano', '459');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('462', 'Grande', 'Grande', '459');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('463', 'Faldas', 'Faldas', '450');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('464', 'Chico', 'Chico', '463');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('465', 'Mediano', 'Mediano', '463');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('466', 'Grande', 'Grande', '463');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('467', 'Pantalones', 'Pantalones', '450');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('468', 'Chico', 'Chico', '467');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('469', 'Mediano', 'Mediano', '467');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('470', 'Grande', 'Grande', '467');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('471', 'Batas', 'Batas', '450');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('472', 'Chico', 'Chico', '471');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('473', 'Mediano', 'Mediano', '471');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('474', 'Grande', 'Grande', '471');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('475', 'Camisas', 'Camisas', '450');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('476', 'Chico', 'Chico', '475');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('477', 'Mediano', 'Mediano', '475');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('478', 'Grande', 'Grande', '475');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('479', 'Playeras', 'Playeras', '450');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('480', 'Chico', 'Chico', '479');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('481', 'Mediano', 'Mediano', '479');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('482', 'Grande', 'Grande', '479');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('483', 'Traje sastre', 'Traje sastre', '450');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('484', 'Chico', 'Chico', '483');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('485', 'Mediano', 'Mediano', '483');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('486', 'Grande', 'Grande', '483');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('487', 'Sueter', 'Sueter', '450');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('488', 'Chico', 'Chico', '487');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('489', 'Mediano', 'Mediano', '487');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('490', 'Grande', 'Grande', '487');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('491', 'Chalecos', 'Chalecos', '450');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('492', 'Chico', 'Chico', '491');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('493', 'Mediano', 'Mediano', '491');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('494', 'Grande', 'Grande', '491');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('495', 'Bermudas', 'Bermudas', '450');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('496', 'Chico', 'Chico', '495');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('497', 'Mediano', 'Mediano', '495');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('498', 'Grande', 'Grande', '495');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('499', 'Ropa interior', 'Ropa interior', '450');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('500', 'Chico', 'Chico', '499');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('501', 'Mediano', 'Mediano', '499');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('502', 'Grande', 'Grande', '499');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('503', 'Deportiva', 'Deportiva', '450');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('504', 'Chico', 'Chico', '503');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('505', 'Mediano', 'Mediano', '503');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('506', 'Grande', 'Grande', '503');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('507', 'Pijamas', 'Pijamas', '450');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('508', 'Chico', 'Chico', '507');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('509', 'Mediano', 'Mediano', '507');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('510', 'Grande', 'Grande', '507');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('511', 'Chamarras', 'Chamarras', '450');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('512', 'Chico', 'Chico', '511');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('513', 'Mediano', 'Mediano', '511');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('514', 'Grande', 'Grande', '511');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('515', 'Abrigos', 'Abrigos', '450');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('516', 'Chico', 'Chico', '515');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('517', 'Mediano', 'Mediano', '515');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('518', 'Grande', 'Grande', '515');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('519', 'Accesorios', 'Accesorios', '450');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('520', 'Pañuelos', 'Pañuelos', '519');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('521', 'Moños', 'Moños', '519');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('522', 'Mascada', 'Mascada', '519');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('523', 'Pashminas', 'Pashminas', '519');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('524', 'Pareos', 'Pareos', '519');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('525', 'Corbatas', 'Corbatas', '519');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('526', 'Bufanda', 'Bufanda', '519');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('527', 'Guantes', 'Guantes', '519');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('528', 'Sombreros', 'Sombreros', '519');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('529', 'Cinturones', 'Cinturones', '519');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('530', 'Calzado', 'Calzado', '450');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('531', 'Botas*', 'Botas*', '530');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('532', 'Tenis*', 'Tenis*', '530');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('533', 'Sandalias*', 'Sandalias*', '530');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('534', 'Pantufla*', 'Pantufla*', '530');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('535', 'Zapato*', 'Zapato*', '530');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('536', 'Especiales*', 'Especiales*', '530');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('537', 'Niña', 'Niña', '449');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('538', 'Blusas', 'Blusas', '537');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('539', 'Chico', 'Chico', '538');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('540', 'Mediano', 'Mediano', '538');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('541', 'Grande', 'Grande', '538');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('542', 'Vestidos', 'Vestidos', '537');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('543', 'Chico', 'Chico', '542');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('544', 'Mediano', 'Mediano', '542');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('545', 'Grande', 'Grande', '542');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('546', 'Vestido de noche', 'Vestido de noche', '537');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('547', 'Chico', 'Chico', '546');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('548', 'Mediano', 'Mediano', '546');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('549', 'Grande', 'Grande', '546');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('550', 'Faldas', 'Faldas', '537');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('551', 'Chico', 'Chico', '550');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('552', 'Mediano', 'Mediano', '550');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('553', 'Grande', 'Grande', '550');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('554', 'Pantalones', 'Pantalones', '537');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('555', 'Chico', 'Chico', '554');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('556', 'Mediano', 'Mediano', '554');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('557', 'Grande', 'Grande', '554');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('558', 'Batas', 'Batas', '537');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('559', 'Chico', 'Chico', '558');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('560', 'Mediano', 'Mediano', '558');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('561', 'Grande', 'Grande', '558');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('562', 'Camisas', 'Camisas', '537');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('563', 'Chico', 'Chico', '562');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('564', 'Mediano', 'Mediano', '562');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('565', 'Grande', 'Grande', '562');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('566', 'Playeras', 'Playeras', '537');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('567', 'Chico', 'Chico', '566');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('568', 'Mediano', 'Mediano', '566');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('569', 'Grande', 'Grande', '566');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('570', 'Traje sastre', 'Traje sastre', '537');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('571', 'Chico', 'Chico', '570');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('572', 'Mediano', 'Mediano', '570');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('573', 'Grande', 'Grande', '570');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('574', 'Sueter', 'Sueter', '537');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('575', 'Chico', 'Chico', '574');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('576', 'Mediano', 'Mediano', '574');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('577', 'Grande', 'Grande', '574');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('578', 'Chalecos', 'Chalecos', '537');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('579', 'Chico', 'Chico', '578');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('580', 'Mediano', 'Mediano', '578');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('581', 'Grande', 'Grande', '578');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('582', 'Bermudas', 'Bermudas', '537');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('583', 'Chico', 'Chico', '582');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('584', 'Mediano', 'Mediano', '582');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('585', 'Grande', 'Grande', '582');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('586', 'Ropa interior', 'Ropa interior', '537');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('587', 'Chico', 'Chico', '586');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('588', 'Mediano', 'Mediano', '586');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('589', 'Grande', 'Grande', '586');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('590', 'Deportiva', 'Deportiva', '537');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('591', 'Chico', 'Chico', '590');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('592', 'Mediano', 'Mediano', '590');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('593', 'Grande', 'Grande', '590');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('594', 'Pijamas', 'Pijamas', '537');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('595', 'Chico', 'Chico', '594');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('596', 'Mediano', 'Mediano', '594');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('597', 'Grande', 'Grande', '594');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('598', 'Chamarras', 'Chamarras', '537');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('599', 'Chico', 'Chico', '598');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('600', 'Mediano', 'Mediano', '598');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('601', 'Grande', 'Grande', '598');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('602', 'Abrigos', 'Abrigos', '537');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('603', 'Chico', 'Chico', '602');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('604', 'Mediano', 'Mediano', '602');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('605', 'Grande', 'Grande', '602');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('606', 'Accesorios', 'Accesorios', '537');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('607', 'Pañuelos', 'Pañuelos', '606');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('608', 'Moños', 'Moños', '606');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('609', 'Mascada', 'Mascada', '606');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('610', 'Pashminas', 'Pashminas', '606');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('611', 'Pareos', 'Pareos', '606');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('612', 'Corbatas', 'Corbatas', '606');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('613', 'Bufanda', 'Bufanda', '606');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('614', 'Guantes', 'Guantes', '606');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('615', 'Sombreros', 'Sombreros', '606');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('616', 'Cinturones', 'Cinturones', '606');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('617', 'Calzado', 'Calzado', '537');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('618', 'Botas*', 'Botas*', '617');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('619', 'Tenis*', 'Tenis*', '617');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('620', 'Sandalias*', 'Sandalias*', '617');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('621', 'Pantufla*', 'Pantufla*', '617');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('622', 'Zapato*', 'Zapato*', '617');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('623', 'Especiales*', 'Especiales*', '617');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('624', 'Uniformes', 'Uniformes', '301');
INSERT INTO `argos`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('625', 'Difraces y botargas', 'Difraces y botargas', '301');
