USE `inventory`;

INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('195', 'Muebles', 'Muebles', NULL);
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('196', 'Bancos', 'Bancos', '195');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('197', 'Sillas', 'Sillas', '195');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('198', 'Metal', 'Metal', '197');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('199', 'Madera', 'Madera', '197');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('200', 'Plástico', 'Plástico', '197');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('201', 'Tapiz', 'Tapiz', '197');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('202', 'Mesas', 'Mesas', '195');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('203', 'Mesas trabajo', 'Mesas trabajo', '202');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('204', 'Mesas periqueras', 'Mesas periqueras', '202');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('205', 'Mesas comensal', 'Mesas comensal', '202');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('206', 'Redondas', 'Redondas', '205');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('207', 'Cuadradas', 'Cuadradas', '205');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('208', 'Irregulares', 'Irregulares', '205');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('209', 'Poligonales', 'Poligonales', '205');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('210', 'Mesas de centro', 'Mesas de centro', '202');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('211', 'Redondas', 'Redondas', '210');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('212', 'Cuadradas', 'Cuadradas', '210');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('213', 'Irregulares', 'Irregulares', '210');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('214', 'Poligonales', 'Poligonales', '210');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('215', 'Mesas de laterales', 'Mesas de laterales', '202');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('216', 'Mesas de esquineras', 'Mesas de esquineras', '202');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('217', 'Mesas de juego', 'Mesas de juego', '202');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('218', 'Muebles de jardín y playa', 'Muebles de jardín y playa', '195');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('219', 'Consolas', 'Consolas', '195');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('220', 'Credenzas', 'Credenzas', '195');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('221', 'Vitrinas', 'Vitrinas', '195');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('222', 'Mostradores', 'Mostradores', '195');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('223', 'Sofá - cama', 'Sofá - cama', '195');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('224', 'Loveseat', 'Loveseat', '195');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('225', 'Sala Modular', 'Sala Modular', '195');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('226', 'Sillón individual', 'Sillón individual', '195');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('227', 'Sillón 3 y 4 plazas', 'Sillón 3 y 4 plazas', '195');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('228', 'Puff', 'Puff', '195');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('229', 'Diván', 'Diván', '195');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('230', 'Taburetes', 'Taburetes', '195');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('231', 'Libreros', 'Libreros', '195');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('232', 'Barras', 'Barras', '195');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('233', 'Gabinetes', 'Gabinetes', '195');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('234', 'Estanterías', 'Estanterías', '195');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('235', 'Lockers', 'Lockers', '234');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('236', 'Racks', 'Racks', '234');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('237', 'Cocina integral', 'Cocina integral', '195');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('238', 'Alacenas', 'Alacenas', '195');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('239', 'Estanterías Lockers', 'Estanterías Lockers', '195');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('240', 'Racks', 'Racks', '195');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('241', 'Retretes', 'Retretes', '195');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('242', 'Mingitorios', 'Mingitorios', '195');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('243', 'Lavabos', 'Lavabos', '195');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('244', 'Tinas', 'Tinas', '195');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('245', 'Cancelería', 'Cancelería', '195');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('246', 'Escritorios', 'Escritorios', '195');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('247', 'Archiveros', 'Archiveros', '195');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('248', 'Bufettes', 'Bufettes', '195');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('249', 'Muebles de tv', 'Muebles de tv', '195');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('250', 'Barras', 'Barras', '195');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('251', 'Camas', 'Camas', '195');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('252', 'Cabecera, pieceras', 'Cabecera, pieceras', '251');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('253', 'Base', 'Base', '251');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('254', 'Colchón', 'Colchón', '251');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('255', 'Cunas', 'Cunas', '251');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('256', 'Literas', 'Literas', '251');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('257', 'Cajoneras', 'Cajoneras', '195');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('258', 'Armarios', 'Armarios', '195');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('259', 'Roperos', 'Roperos', '195');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('260', 'Buroes', 'Buroes', '195');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('261', 'Tocadores', 'Tocadores', '195');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('262', 'Jugueteros', 'Jugueteros', '195');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('263', 'Bancas', 'Bancas', '195');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('264', 'Muebles de hospital', 'Muebles de hospital', '195');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('265', 'Especiales', 'Especiales', '195');
