USE `inventory`;

INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('266', 'Utilería', 'Utilería', NULL);
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('267', 'Escritura', 'Escritura', '266');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('268', 'Joyería', 'Joyería', '266');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('269', 'Maculina', 'Maculina', '268');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('270', 'Femenina', 'Femenina', '268');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('271', 'Relojes de pulso', 'Relojes de pulso', '266');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('272', 'Gadget', 'Gadget', '266');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('273', 'Laptop', 'Laptop', '272');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('274', 'Tabletas', 'Tabletas', '272');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('275', 'Iphode', 'Iphode', '272');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('276', 'Biper', 'Biper', '272');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('277', 'Celulares', 'Celulares', '272');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('278', 'Grabadoras', 'Grabadoras', '272');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('279', 'Audio portátiles', 'Audio portátiles', '272');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('280', 'Audífonos', 'Audífonos', '272');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('281', 'Carcasas', 'Carcasas', '266');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('282', 'Portafolios', 'Portafolios', '266');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('283', 'Maletas', 'Maletas', '266');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('284', 'Mochilas', 'Mochilas', '266');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('285', 'Bolsos', 'Bolsos', '266');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('286', 'Carteras', 'Carteras', '266');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('287', 'Llaveros', 'Llaveros', '266');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('288', 'Gafetes', 'Gafetes', '266');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('289', 'Dinero', 'Dinero', '266');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('290', 'Placas oficiales', 'Placas oficiales', '266');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('291', 'Paraguas', 'Paraguas', '266');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('292', 'Bastones', 'Bastones', '266');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('293', 'Lentes', 'Lentes', '266');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('294', 'Gafas', 'Gafas', '266');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('295', 'Artículos de belleza', 'Artículos de belleza', '266');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('296', 'Artículos de limpieza', 'Artículos de limpieza', '266');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('297', 'Equipo fotográfico', 'Equipo fotográfico', '266');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('298', 'Chapuzas', 'Chapuzas', '266');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('299', 'Armas', 'Armas', '266');
INSERT INTO `inventory`.`category` (`category_id`, `name`, `description`, `parent_category`) VALUES ('300', 'Otros', 'Otros', '266');
